### ISSUE TITLE
Public API unregister not defined

### ISSUE THREAD

**Issue by arthur-er** [coddingtonbear/obsidian-local-rest-api-sample-api-extension#1]
`api.unregister` is called on [`onunload()`](https://github.com/coddingtonbear/obsidian-local-rest-api-sample-api-extension/blob/705f69e34aa72a51803ec79b17f8e7d52fbee9a6/main.ts#L52)  but it isn't defined

**Comment by coddingtonbear** [comment]
Try to `npm i --upgrade obsidian-local-rest-api` again -- I've just pushed up a new version of the package (2.5.4).

**Comment by arthur-er** [comment]
Now working!
